version: '3.4'

services:
  gcc:
    image: gcc
    build:
      context: .
      dockerfile: environment/compilation/Dockerfile
      args:
        CC: gcc-11
        CXX: g++-11
    volumes:
      - ./out/gcc:/usr/ostl/ostl/out
  clang:
    image: clang
    build:
      context: .
      dockerfile: environment/compilation/Dockerfile
      args:
        CC: clang-14
        CXX: clang++-14
    volumes:
      - ./out/clang:/usr/ostl/ostl/out
