#include "caldera/glfw/glfw_utils.hpp"

#include <GLFW/glfw3.h>

namespace caldera
{
    glass::keyboard::key glfw_key_convert(int key)
    {
        switch (key)
        {
            case GLFW_KEY_ESCAPE:
                return glass::keyboard::key::escape;
            case GLFW_KEY_F1:
                return glass::keyboard::key::f1;
            case GLFW_KEY_F2:
                return glass::keyboard::key::f2;
            case GLFW_KEY_F3:
                return glass::keyboard::key::f3;
            case GLFW_KEY_F4:
                return glass::keyboard::key::f4;
            case GLFW_KEY_F5:
                return glass::keyboard::key::f5;
            case GLFW_KEY_F6:
                return glass::keyboard::key::f6;
            case GLFW_KEY_F7:
                return glass::keyboard::key::f7;
            case GLFW_KEY_F8:
                return glass::keyboard::key::f8;
            case GLFW_KEY_F9:
                return glass::keyboard::key::f9;
            case GLFW_KEY_F10:
                return glass::keyboard::key::f10;
            case GLFW_KEY_F11:
                return glass::keyboard::key::f11;
            case GLFW_KEY_F12:
                return glass::keyboard::key::f12;

            case GLFW_KEY_GRAVE_ACCENT:
                return glass::keyboard::key::backquote;
            case GLFW_KEY_1:
                return glass::keyboard::key::one;
            case GLFW_KEY_2:
                return glass::keyboard::key::two;
            case GLFW_KEY_3:
                return glass::keyboard::key::three;
            case GLFW_KEY_4:
                return glass::keyboard::key::four;
            case GLFW_KEY_5:
                return glass::keyboard::key::five;
            case GLFW_KEY_6:
                return glass::keyboard::key::six;
            case GLFW_KEY_7:
                return glass::keyboard::key::seven;
            case GLFW_KEY_8:
                return glass::keyboard::key::eight;
            case GLFW_KEY_9:
                return glass::keyboard::key::nine;
            case GLFW_KEY_0:
                return glass::keyboard::key::zero;
            case GLFW_KEY_MINUS:
                return glass::keyboard::key::hyphen_minus;
            case GLFW_KEY_EQUAL:
                return glass::keyboard::key::equal;

            case GLFW_KEY_TAB:
                return glass::keyboard::key::tab;
            case GLFW_KEY_Q:
                return glass::keyboard::key::q;
            case GLFW_KEY_W:
                return glass::keyboard::key::w;
            case GLFW_KEY_E:
                return glass::keyboard::key::e;
            case GLFW_KEY_R:
                return glass::keyboard::key::r;
            case GLFW_KEY_T:
                return glass::keyboard::key::t;
            case GLFW_KEY_Y:
                return glass::keyboard::key::y;
            case GLFW_KEY_U:
                return glass::keyboard::key::u;
            case GLFW_KEY_I:
                return glass::keyboard::key::i;
            case GLFW_KEY_O:
                return glass::keyboard::key::o;
            case GLFW_KEY_P:
                return glass::keyboard::key::p;
            case GLFW_KEY_LEFT_BRACKET:
                return glass::keyboard::key::left_bracket;
            case GLFW_KEY_RIGHT_BRACKET:
                return glass::keyboard::key::right_bracket;
            case GLFW_KEY_ENTER:
                return glass::keyboard::key::enter;

            case GLFW_KEY_CAPS_LOCK:
                return glass::keyboard::key::caps_lock;
            case GLFW_KEY_A:
                return glass::keyboard::key::a;
            case GLFW_KEY_S:
                return glass::keyboard::key::s;
            case GLFW_KEY_D:
                return glass::keyboard::key::d;
            case GLFW_KEY_F:
                return glass::keyboard::key::f;
            case GLFW_KEY_G:
                return glass::keyboard::key::g;
            case GLFW_KEY_H:
                return glass::keyboard::key::h;
            case GLFW_KEY_J:
                return glass::keyboard::key::j;
            case GLFW_KEY_K:
                return glass::keyboard::key::k;
            case GLFW_KEY_L:
                return glass::keyboard::key::l;
            case GLFW_KEY_SEMICOLON:
                return glass::keyboard::key::semicolon;
            case GLFW_KEY_APOSTROPHE:
                return glass::keyboard::key::apostrophe;
            case GLFW_KEY_BACKSLASH:
                return glass::keyboard::key::sharp;

            case GLFW_KEY_LEFT_SHIFT:
                return glass::keyboard::key::left_shift;
            case GLFW_KEY_WORLD_2:
                return glass::keyboard::key::backslash;
            case GLFW_KEY_Z:
                return glass::keyboard::key::z;
            case GLFW_KEY_X:
                return glass::keyboard::key::x;
            case GLFW_KEY_C:
                return glass::keyboard::key::c;
            case GLFW_KEY_V:
                return glass::keyboard::key::v;
            case GLFW_KEY_B:
                return glass::keyboard::key::b;
            case GLFW_KEY_N:
                return glass::keyboard::key::n;
            case GLFW_KEY_M:
                return glass::keyboard::key::m;
            case GLFW_KEY_COMMA:
                return glass::keyboard::key::comma;
            case GLFW_KEY_PERIOD:
                return glass::keyboard::key::period;
            case GLFW_KEY_SLASH:
                return glass::keyboard::key::slash;
            case GLFW_KEY_RIGHT_SHIFT:
                return glass::keyboard::key::right_shift;

            case GLFW_KEY_LEFT_CONTROL:
                return glass::keyboard::key::left_control;
            case GLFW_KEY_LEFT_SUPER:
                return glass::keyboard::key::left;
            case GLFW_KEY_LEFT_ALT:
                return glass::keyboard::key::left_alt;
            case GLFW_KEY_SPACE:
                return glass::keyboard::key::space;
            case GLFW_KEY_RIGHT_ALT:
                return glass::keyboard::key::right_alt;
            case GLFW_KEY_RIGHT_SUPER:
                return glass::keyboard::key::right_super;
            case GLFW_KEY_MENU:
                return glass::keyboard::key::menu;
            case GLFW_KEY_RIGHT_CONTROL:
                return glass::keyboard::key::right_control;

            case GLFW_KEY_PRINT_SCREEN:
                return glass::keyboard::key::screen_capture;
            case GLFW_KEY_SCROLL_LOCK:
                return glass::keyboard::key::scroll_lock;
            case GLFW_KEY_PAUSE:
                return glass::keyboard::key::pause;
            case GLFW_KEY_INSERT:
                return glass::keyboard::key::insert;
            case GLFW_KEY_HOME:
                return glass::keyboard::key::start;
            case GLFW_KEY_PAGE_UP:
                return glass::keyboard::key::page_up;
            case GLFW_KEY_DELETE:
                return glass::keyboard::key::del;
            case GLFW_KEY_END:
                return glass::keyboard::key::end;
            case GLFW_KEY_PAGE_DOWN:
                return glass::keyboard::key::page_down;

            case GLFW_KEY_UP:
                return glass::keyboard::key::up;
            case GLFW_KEY_LEFT:
                return glass::keyboard::key::left;
            case GLFW_KEY_DOWN:
                return glass::keyboard::key::down;
            case GLFW_KEY_RIGHT:
                return glass::keyboard::key::right;

            case GLFW_KEY_NUM_LOCK:
                return glass::keyboard::key::num_lock;
            case GLFW_KEY_KP_DIVIDE:
                return glass::keyboard::key::divide;
            case GLFW_KEY_KP_MULTIPLY:
                return glass::keyboard::key::multiply;
            case GLFW_KEY_KP_SUBTRACT:
                return glass::keyboard::key::substract;
            case GLFW_KEY_KP_7:
                return glass::keyboard::key::key_pad_7;
            case GLFW_KEY_KP_8:
                return glass::keyboard::key::key_pad_8;
            case GLFW_KEY_KP_9:
                return glass::keyboard::key::key_pad_9;
            case GLFW_KEY_KP_ADD:
                return glass::keyboard::key::add;
            case GLFW_KEY_KP_4:
                return glass::keyboard::key::key_pad_4;
            case GLFW_KEY_KP_5:
                return glass::keyboard::key::key_pad_5;
            case GLFW_KEY_KP_6:
                return glass::keyboard::key::key_pad_6;
            case GLFW_KEY_KP_1:
                return glass::keyboard::key::key_pad_1;
            case GLFW_KEY_KP_2:
                return glass::keyboard::key::key_pad_2;
            case GLFW_KEY_KP_3:
                return glass::keyboard::key::key_pad_3;
            case GLFW_KEY_KP_ENTER:
                return glass::keyboard::key::key_pad_enter;
            case GLFW_KEY_KP_0:
                return glass::keyboard::key::key_pad_0;
            case GLFW_KEY_KP_DECIMAL:
                return glass::keyboard::key::key_pad_decimal;

            default:
                return glass::keyboard::key::unknown;
        }
    }
}  // namespace caldera