macro(glob_subdirectory _directory)
    file(GLOB children RELATIVE "${_directory}" "${_directory}/*")
    foreach(child ${children})
        if (IS_DIRECTORY "${_directory}/${child}" AND NOT "${child}" STREQUAL "CMakeFiles")
            message(STATUS "\tincluding ${child}")
            add_subdirectory(${child})
        endif()
    endforeach()
endmacro()